name: build-package

on:
  push:
    paths:
      - '.github/actions/native-lib-build/action.yml'
      - '.github/workflows/build-and-release-package.yml'
      - '.github/workflows/build-package.yml'
      - 'assembly-lib.xml'
      - 'assembly-package.xml'
      - 'CMakeLists.txt'
      - 'pom.xml'
      - 'scripts/install-deps-and-build-native-lib.sh'
      - 'src/**'
  pull_request:
    paths:
      - '.github/actions/native-lib-build/action.yml'
      - '.github/workflows/build-and-release-package.yml'
      - '.github/workflows/build-package.yml'
      - 'assembly-lib.xml'
      - 'assembly-package.xml'
      - 'CMakeLists.txt'
      - 'pom.xml'
      - 'scripts/install-deps-and-build-native-lib.sh'
      - 'src/**'
  workflow_dispatch:

concurrency: build-${{github.ref}}

jobs:
  build-lib-for-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - run: >-
          docker run
          --rm
          --platform linux/arm64
          --mount type=bind,source=${{ github.workspace }},target=/mnt/clp
          --workdir /mnt/clp
          eclipse-temurin:11-jdk-focal
          ./scripts/install-deps-and-build-native-lib.sh

      - uses: actions/upload-artifact@v4
        with:
          name: libclp-ffi-java-linux-arm64
          path: ${{github.workspace}}/target/clp-ffi-*-native-lib/
          if-no-files-found: error
          retention-days: 1

  build-lib-for-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install requirements
        run: brew install cmake gcc java11 maven

      - name: Build native library
        id: build
        uses: ./.github/actions/native-lib-build

      - uses: actions/upload-artifact@v4
        with:
          name: libclp-ffi-java-macos
          path: ${{github.workspace}}/clp-ffi-*-native-lib/
          if-no-files-found: error
          retention-days: 1

  build-package:
    needs:
      - build-lib-for-linux-arm64
      - build-lib-for-macos
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: 'github'

      - name: Install requirements
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - name: Build native library for Linux
        id: build
        uses: ./.github/actions/native-lib-build

      - uses: actions/download-artifact@v4
        with:
          name: libclp-ffi-java-linux-arm64
          path: ./target/.

      - uses: actions/download-artifact@v4
        with:
          name: libclp-ffi-java-macos
          path: ./target/.

      - name: Build package and run tests
        run: mvn --batch-mode test

      - name: Deploy to GitHub
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: mvn --batch-mode deploy -DskipTests -Pgithub_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
